save:
  fields:
    area_id:
      required: false
      selector:
        area:
    name:
      required: false
      selector:
        text:
    scene:
      required: false
      selector:
        entity:
          domain: scene
rename:
  fields:
    scene:
      required: true
      selector:
        entity:
          domain: scene
    name:
      required: true
      selector:
        text:
delete:
  fields:
    scene:
      required: true
      selector:
        entity:
          domain: scene
create:
  fields:
    name:
      required: true
      selector:
        text:
    brightness:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    area_id:
      required: false
      selector:
        area:
          multiple: true
    levels:
      required: false
      selector:
        object:
    replace:
      required: false
      default: false
      selector:
        boolean:
    color_temp_kelvin:
      required: false
      selector:
        color_temp:
          unit: kelvin
          min: 1000
          max: 10000
    whites:
      required: false
      selector:
        object:
